### ISSUE TITLE
Hg Alias with folder path containing spaces throws Mercurial.MercurialExecutionException: The system cannot find the file specified

### ISSUE THREAD

**Issue by CruelTaskmaster** [vCipher/Cake.Hg#17]
When calling the Hg alias with a folder path container spaces (e.g. C:\New folder\Repo), an exception is thrown.

## Expected Behavior
A new Repository class is created.

## Current Behavior
The following exception is thrown:
> Mercurial.MercurialExecutionException: abort: The system cannot find the file specified: 'C:\New'
> 
>    at Mercurial.CommandBase`1.ThrowOnUnsuccessfulExecution(Int32 exitCode, String standardErrorOutput)
>    at Mercurial.CommandBase`1.After(Int32 exitCode, String standardOutput, String standardErrorOutput)
>    at Mercurial.CommandProcessor.Execute(String workingDirectory, String executable, ICommand command, KeyValuePair`2[] environmentVariables, IEnumerable`1 specialArguments)
>    at Mercurial.NonPersistentClient.Execute(String repositoryPath, IMercurialCommand command)
>    at Mercurial.Configuration.ClientConfigurationCollection.Refresh(String currentWorkingDirectory)
>    at Mercurial.AutoSwitchingClientFactory.CreateClient(String repositoryPath)
>    at Mercurial.Repository..ctor(String rootPath, IClientFactory clientFactory)
>    at Cake.Hg.HgAliases.Hg(ICakeContext context, DirectoryPath repositoryPath)
>    at Submission#0.Hg(DirectoryPath repositoryPath)
>    at Submission#0.<<Initialize>>b__0_0(ICakeContext context)
>    at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
>    at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()

## Possible Solution
After digging through the Mercurial.Net.dll, I have found that the issue is caused by line in `ClientConfigurationCollection.Refresh(string currentWorkingDirectory = null)`:

```
showConfigCommand.AddArgument(string.Format("--cwd {0}", (object)currentWorkingDirectory));
```

The solution is to simply add quotes around the provided working directory:
```
showConfigCommand.AddArgument(string.Format("--cwd \"{0}\"", (object)currentWorkingDirectory));
```

## Steps to Reproduce (for bugs)

1. Create Cake file
2. Create a folder containing spaces (e.g. "C:\New folder\Repo")
3. Create Hg alias with the create folder path (can be absolute or relative).
4. Run cake build

## Context

This severely limits the flexibility of folder structures allowed when creating repositories for the build process.

## Your Environment

* Addin version used: 0.2.0
* Cake Version used: 0.35
* Operating System: Windows 10 Enterprise

**Comment by phantomtypist** [comment]
Yeah, this is more or less a bug in https://github.com/hgtools/Hg.Net

I'll open up some bandwidth and fix it tomorrow afternoon EDT.

**Comment by phantomtypist** [comment]
Oddly enough I never ran across that one bug because we kebab-case everything :)

**Comment by phantomtypist** [comment]
https://github.com/hgtools/Hg.Net/blob/15aac7a577fdcbba484d4ff1a280a5dce994a31d/src/Mercurial.Net/Configuration/ClientConfigurationCollection.cs#L110
